### PR TITLE
Rewrite parseIf

### PR DESCRIPTION
**Pull request by lulucca12**
Used `mfilter :: MonadPlus m => (a -> Bool) -> m a -> m a` as Maybe has an automatic instance of MonadPlus derived from the instance of Alternative.

### CODE REVIEW

**Comment by rexim** [comment]
@lulucca12 hey! Thanks for the Pull Request, unfortunately it doesn't add any new functionality to the parser. Please check https://github.com/tsoding/haskell-json#contribution-notes for more information.

**Comment by lulucca12** [comment]
@rexim I don't see the meaning of this. Isn't what I did the exact same thing as #4 did? Rewrite the implemetation without adding fuctionality and it got merged?
Besides isn't that what managers are for? I remember one time when Linus Torvalds said about his bad actions at the Linux maling list as he invented git the way he did for being able to pass his work to others.
So why don't just elect a manager or be more liberal about it and enable merging without supervision, just reviewing?

**Comment by rexim** [comment]
@lulucca12 #4 was submitted before e886bfb1c1fdb3bccef0aba661720df010683919

**Comment by lulucca12** [comment]
@rexim does that mean that you changed the rules in the middle of the game?
Fine, thats why it is open source ;)

**Pull request closed without merging**
